blank_issues_enabled: false
contact_links:
  - name: Community Guidelines
    url: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
    about: Please make sure to follow the PSF Code of Conduct when participating in this repository.
